[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]
# Uncomment for flash+debug via probe-rs (SWD required):
# runner = "probe-rs run --chip STM32F413VGTx"

[build]
target = "thumbv7em-none-eabihf"
